on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.19'
          - '1.18'

    steps:
      - uses: actions/setup-go@v3
        with:
            go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - run: go test -v -coverprofile=profile.cov ./...

#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#          version: v1.50.1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
